"""Probatio: put your data to the proof.

Probatio validates Python data structures against a schema. It is a modern,
maintained data validation library that is API-compatible with voluptuous, so
it can be dropped in where voluptuous is used, while being free to improve the
internals, error model, and tooling underneath.

This module is the public facade: it re-exports the schema engine, markers,
validators, the error hierarchy, the JSON Schema / OpenAPI / field-list codecs,
and the JSON/YAML/TOML loaders and dumpers.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

from probatio._compile_policy import (
    CompilePolicy,
    get_compile_policy,
    set_compile_policy,
)
from probatio._type_registry import (
    clear_type_registry,
    register_type,
    type_registry,
)
from probatio.dataclass_schema import (
    DataclassSchema,
    TypedDictSchema,
    create_dataclass_schema,
    create_typeddict_schema,
    is_dataclass,
)
from probatio.error import (
    AllInvalid,
    AnyInvalid,
    BlockDeviceInvalid,
    BooleanInvalid,
    CoerceInvalid,
    ContainsInvalid,
    DateInvalid,
    DatetimeInvalid,
    DictInvalid,
    DirInvalid,
    DurationInvalid,
    EmailInvalid,
    EnumInvalid,
    EpochInvalid,
    Error,
    ExactSequenceInvalid,
    ExclusiveInvalid,
    ExtraKeysInvalid,
    FalseInvalid,
    FifoInvalid,
    FileInvalid,
    HostnameInvalid,
    ImmutableInvalid,
    InclusiveInvalid,
    InInvalid,
    Invalid,
    IpInvalid,
    JsonInvalid,
    LengthInvalid,
    LiteralInvalid,
    Location,
    MacAddressInvalid,
    MatchInvalid,
    MultipleInvalid,
    MultipleOfInvalid,
    NotEnoughValid,
    NotInInvalid,
    ObjectInvalid,
    PathInvalid,
    RangeInvalid,
    RequiredFieldInvalid,
    ScalarInvalid,
    SchemaError,
    SecretInvalid,
    SequenceTypeInvalid,
    SlugInvalid,
    SocketInvalid,
    SymlinkInvalid,
    TimeInvalid,
    TimeZoneInvalid,
    TooManyValid,
    TrueInvalid,
    TypeInvalid,
    UrlInvalid,
    UuidInvalid,
    ValueInvalid,
    YamlInvalid,
)
from probatio.markers import (
    UNDEFINED,
    Alias,
    Exclusive,
    Extra,
    Forbidden,
    Inclusive,
    Marker,
    Object,
    Optional,
    Remove,
    Required,
    Self,
    Undefined,
    default_factory,
)
from probatio.schema import (
    ALLOW_EXTRA,
    PREVENT_EXTRA,
    REMOVE_EXTRA,
    Schema,
    Schemable,
    current_context,
)
from probatio.validators import (
    ASCII,
    E164,
    IBAN,
    ULID,
    UUID,
    All,
    AllOrNone,
    Alpha,
    Alphanumeric,
    And,
    Any,
    AsDate,
    AsDatetime,
    AsTime,
    AtLeastOne,
    AtMostOne,
    Base64,
    Boolean,
    Byte,
    ByteLength,
    Capitalize,
    Check,
    Clamp,
    Coerce,
    Contains,
    CreditCard,
    DataURI,
    Date,
    Datetime,
    DefaultTo,
    Duration,
    Email,
    EndsWith,
    EnsureList,
    Epoch,
    Equal,
    ExactlyOne,
    ExactSequence,
    Fqdn,
    FqdnUrl,
    Hex,
    HexColor,
    HexInt,
    Hostname,
    Immutable,
    In,
    IPAddress,
    IPNetwork,
    IPv4Address,
    IPv6Address,
    IsBlockDevice,
    IsDir,
    IsFalse,
    IsFifo,
    IsFile,
    IsRegex,
    IsSocket,
    IsSymlink,
    IsTrue,
    JSONString,
    Latitude,
    Length,
    Literal,
    Longitude,
    Lower,
    MacAddress,
    Match,
    Maybe,
    Msg,
    MultipleOf,
    Negative,
    NonEmpty,
    NonNegative,
    NotIn,
    NoWhitespace,
    Number,
    Or,
    PathExists,
    Percentage,
    Port,
    Positive,
    PrintableASCII,
    Range,
    Replace,
    RequiredIf,
    RequiredWith,
    RequiredWithout,
    Secret,
    SecretValue,
    Set,
    SetTo,
    Slug,
    SmallFloat,
    SomeOf,
    Sorted,
    StartsWith,
    Strip,
    Switch,
    Time,
    TimeZone,
    Title,
    Union,
    Unique,
    Unordered,
    Upper,
    Url,
    WriteOnce,
    YAMLString,
    message,
    raises,
    truth,
    validate,
)

if TYPE_CHECKING:
    # Eagerly visible to type-checkers so ``probatio.to_json_schema`` and friends
    # keep their real signatures, while at runtime they are re-exported lazily
    # (below) to keep a validate-only import cheap.
    from probatio.codecs import (
        UNSUPPORTED,
        from_json_schema,
        from_openapi,
        serialize,
        to_json_schema,
        to_openapi,
    )
    from probatio.serde import (
        clear_default_options,
        default_options,
        dump,
        dump_json,
        dump_toml,
        dump_yaml,
        load,
        load_json,
        load_toml,
        load_yaml,
        load_yaml_with_locations,
        set_default_options,
    )

# The codec and serde layers cost more to import than the validation engine, and a
# plain ``import probatio`` for validation needs neither. Their public names are
# re-exported lazily (PEP 562): the submodule is imported on first access of one of
# its names, and the resolved attribute is cached as a real module global so later
# reads are free. Maps each re-exported name to the module it lives in.
_LAZY_NAMES = dict.fromkeys(
    (
        "UNSUPPORTED",
        "from_json_schema",
        "from_openapi",
        "serialize",
        "to_json_schema",
        "to_openapi",
    ),
    "probatio.codecs",
) | dict.fromkeys(
    (
        "clear_default_options",
        "default_options",
        "dump",
        "dump_json",
        "dump_toml",
        "dump_yaml",
        "load",
        "load_json",
        "load_toml",
        "load_yaml",
        "load_yaml_with_locations",
        "set_default_options",
    ),
    "probatio.serde",
)


# ``__version__`` is resolved lazily from the installed package metadata on first
# access (PEP 562). A plain ``import probatio`` for validation never reads it, so
# it should not pay for the metadata lookup, which scans the installed dist-info
# (~20 ms). The resolved value is cached as a real module global afterwards. It
# falls back to "0.0.0" for a bare source-tree import (no install); the release
# workflow stamps the real version at publish time.
def __getattr__(name: str) -> object:
    """Resolve ``__version__`` and the lazy codec/serde re-exports on first access."""
    if name == "__version__":
        from importlib import metadata  # noqa: PLC0415

        try:
            version = metadata.version("probatio")
        except metadata.PackageNotFoundError:  # pragma: no cover
            version = "0.0.0"
        globals()["__version__"] = version
        return version
    module_name = _LAZY_NAMES.get(name)
    if module_name is not None:
        from importlib import import_module  # noqa: PLC0415

        value = getattr(import_module(module_name), name)
        globals()[name] = value
        return value
    message = f"module {__name__!r} has no attribute {name!r}"
    raise AttributeError(message)


__all__ = [
    "ALLOW_EXTRA",
    "ASCII",
    "E164",
    "IBAN",
    "PREVENT_EXTRA",
    "REMOVE_EXTRA",
    "ULID",
    "UNDEFINED",
    "UNSUPPORTED",
    "UUID",
    "Alias",
    "All",
    "AllInvalid",
    "AllOrNone",
    "Alpha",
    "Alphanumeric",
    "And",
    "Any",
    "AnyInvalid",
    "AsDate",
    "AsDatetime",
    "AsTime",
    "AtLeastOne",
    "AtMostOne",
    "Base64",
    "BlockDeviceInvalid",
    "Boolean",
    "BooleanInvalid",
    "Byte",
    "ByteLength",
    "Capitalize",
    "Check",
    "Clamp",
    "Coerce",
    "CoerceInvalid",
    "CompilePolicy",
    "Contains",
    "ContainsInvalid",
    "CreditCard",
    "DataURI",
    "DataclassSchema",
    "Date",
    "DateInvalid",
    "Datetime",
    "DatetimeInvalid",
    "DefaultTo",
    "DictInvalid",
    "DirInvalid",
    "Duration",
    "DurationInvalid",
    "Email",
    "EmailInvalid",
    "EndsWith",
    "EnsureList",
    "EnumInvalid",
    "Epoch",
    "EpochInvalid",
    "Equal",
    "Error",
    "ExactSequence",
    "ExactSequenceInvalid",
    "ExactlyOne",
    "Exclusive",
    "ExclusiveInvalid",
    "Extra",
    "ExtraKeysInvalid",
    "FalseInvalid",
    "FifoInvalid",
    "FileInvalid",
    "Forbidden",
    "Fqdn",
    "FqdnUrl",
    "Hex",
    "HexColor",
    "HexInt",
    "Hostname",
    "HostnameInvalid",
    "IPAddress",
    "IPNetwork",
    "IPv4Address",
    "IPv6Address",
    "Immutable",
    "ImmutableInvalid",
    "In",
    "InInvalid",
    "Inclusive",
    "InclusiveInvalid",
    "Invalid",
    "IpInvalid",
    "IsBlockDevice",
    "IsDir",
    "IsFalse",
    "IsFifo",
    "IsFile",
    "IsRegex",
    "IsSocket",
    "IsSymlink",
    "IsTrue",
    "JSONString",
    "JsonInvalid",
    "Latitude",
    "Length",
    "LengthInvalid",
    "Literal",
    "LiteralInvalid",
    "Location",
    "Longitude",
    "Lower",
    "MacAddress",
    "MacAddressInvalid",
    "Marker",
    "Match",
    "MatchInvalid",
    "Maybe",
    "Msg",
    "MultipleInvalid",
    "MultipleOf",
    "MultipleOfInvalid",
    "Negative",
    "NoWhitespace",
    "NonEmpty",
    "NonNegative",
    "NotEnoughValid",
    "NotIn",
    "NotInInvalid",
    "Number",
    "Object",
    "ObjectInvalid",
    "Optional",
    "Or",
    "PathExists",
    "PathInvalid",
    "Percentage",
    "Port",
    "Positive",
    "PrintableASCII",
    "Range",
    "RangeInvalid",
    "Remove",
    "Replace",
    "Required",
    "RequiredFieldInvalid",
    "RequiredIf",
    "RequiredWith",
    "RequiredWithout",
    "ScalarInvalid",
    "Schema",
    "SchemaError",
    "Schemable",
    "Secret",
    "SecretInvalid",
    "SecretValue",
    "Self",
    "SequenceTypeInvalid",
    "Set",
    "SetTo",
    "Slug",
    "SlugInvalid",
    "SmallFloat",
    "SocketInvalid",
    "SomeOf",
    "Sorted",
    "StartsWith",
    "Strip",
    "Switch",
    "SymlinkInvalid",
    "Time",
    "TimeInvalid",
    "TimeZone",
    "TimeZoneInvalid",
    "Title",
    "TooManyValid",
    "TrueInvalid",
    "TypeInvalid",
    "TypedDictSchema",
    "Undefined",
    "Union",
    "Unique",
    "Unordered",
    "Upper",
    "Url",
    "UrlInvalid",
    "UuidInvalid",
    "ValueInvalid",
    "WriteOnce",
    "YAMLString",
    "YamlInvalid",
    "__version__",
    "clear_default_options",
    "clear_type_registry",
    "create_dataclass_schema",
    "create_typeddict_schema",
    "current_context",
    "default_factory",
    "default_options",
    "dump",
    "dump_json",
    "dump_toml",
    "dump_yaml",
    "from_json_schema",
    "from_openapi",
    "get_compile_policy",
    "is_dataclass",
    "load",
    "load_json",
    "load_toml",
    "load_yaml",
    "load_yaml_with_locations",
    "message",
    "raises",
    "register_type",
    "serialize",
    "set_compile_policy",
    "set_default_options",
    "to_json_schema",
    "to_openapi",
    "truth",
    "type_registry",
    "validate",
]
