"""Probatio: put your data to the proof.

Probatio validates Python data structures against a schema. It is a modern,
maintained data validation library that is API-compatible with voluptuous, so
it can be dropped in where voluptuous is used, while being free to improve the
internals, error model, and tooling underneath.

This module is the public facade: it re-exports the schema engine, markers,
validators, the error hierarchy, and the JSON Schema / OpenAPI / field-list
codecs. Parsing and serialization are the caller's job: validate the parsed
Python object, and use your own loader or dumper around it.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

from probatio._build_policy import (
    BuildPolicy,
    get_build_policy,
    set_build_policy,
)
from probatio._compile_policy import (
    CompilePolicy,
    get_compile_policy,
    set_compile_policy,
)
from probatio.dataclass_schema import (
    DataclassSchema,
    TypedDictSchema,
    create_dataclass_schema,
    create_typeddict_schema,
    is_dataclass,
)
from probatio.decorator import probatio
from probatio.error import (
    AllInvalid,
    AnyInvalid,
    BlockDeviceInvalid,
    BooleanInvalid,
    CoerceInvalid,
    ContainsInvalid,
    DateInvalid,
    DatetimeInvalid,
    DictInvalid,
    DirInvalid,
    DurationInvalid,
    EmailInvalid,
    EnumInvalid,
    EpochInvalid,
    Error,
    ExactSequenceInvalid,
    ExclusiveInvalid,
    ExtraKeysInvalid,
    FalseInvalid,
    FifoInvalid,
    FileInvalid,
    HostnameInvalid,
    ImmutableInvalid,
    InclusiveInvalid,
    InInvalid,
    Invalid,
    IpInvalid,
    JsonInvalid,
    LengthInvalid,
    LiteralInvalid,
    Location,
    MacAddressInvalid,
    MatchInvalid,
    MultipleInvalid,
    MultipleOfInvalid,
    NotEnoughValid,
    NotInInvalid,
    ObjectInvalid,
    PathInvalid,
    RangeInvalid,
    RequiredFieldInvalid,
    ScalarInvalid,
    SchemaError,
    SequenceTypeInvalid,
    SlugInvalid,
    SocketInvalid,
    SymlinkInvalid,
    TimeInvalid,
    TimeZoneInvalid,
    TooManyValid,
    TrueInvalid,
    TypeInvalid,
    UrlInvalid,
    UuidInvalid,
    ValueInvalid,
)
from probatio.fields import Key
from probatio.markers import (
    UNDEFINED,
    Alias,
    Exclusive,
    Extra,
    Forbidden,
    Inclusive,
    Marker,
    Object,
    Optional,
    Remove,
    Required,
    Secret,
    Self,
    Undefined,
    VirtualPathComponent,
    default_factory,
    extra,
)
from probatio.model import SchemaMixin
from probatio.schema import (
    ALLOW_EXTRA,
    PREVENT_EXTRA,
    REMOVE_EXTRA,
    Schema,
    Schemable,
    current_context,
)
from probatio.validators import (
    ASCII,
    E164,
    IBAN,
    ULID,
    UUID,
    Abs,
    All,
    AllOrNone,
    Alpha,
    Alphanumeric,
    And,
    Any,
    AsDate,
    AsDatetime,
    AsTime,
    AsTimedelta,
    AsTimezone,
    AtLeastOne,
    AtMostOne,
    Base64,
    Boolean,
    Byte,
    ByteLength,
    Capitalize,
    Check,
    Clamp,
    Coerce,
    Contains,
    CreditCard,
    DataURI,
    Date,
    Datetime,
    Dedupe,
    DefaultTo,
    Divide,
    Duration,
    Email,
    EndsWith,
    EnsureList,
    Equal,
    ExactlyOne,
    ExactSequence,
    First,
    Fqdn,
    FqdnUrl,
    FromEpoch,
    FromJSONString,
    FromPercentage,
    Hex,
    HexColor,
    HexInt,
    Hostname,
    Immutable,
    In,
    IPAddress,
    IPNetwork,
    IPv4Address,
    IPv6Address,
    IsBlockDevice,
    IsDir,
    IsFalse,
    IsFifo,
    IsFile,
    IsRegex,
    IsSocket,
    IsSymlink,
    IsTrue,
    Join,
    JSONString,
    Last,
    Latitude,
    Length,
    Literal,
    Longitude,
    Lower,
    MacAddress,
    Match,
    Maybe,
    Modulo,
    Msg,
    MultipleOf,
    Multiply,
    Negative,
    NonEmpty,
    NonNegative,
    NormalizeMacAddress,
    NotIn,
    NoWhitespace,
    Number,
    Offset,
    Or,
    PathExists,
    Percentage,
    Port,
    Positive,
    PrintableASCII,
    Range,
    Remap,
    Replace,
    RequiredIf,
    RequiredWith,
    RequiredWithout,
    Round,
    RoundDown,
    RoundUp,
    Scale,
    Set,
    SetTo,
    Slug,
    SmallFloat,
    Snap,
    SomeOf,
    Sort,
    Sorted,
    Split,
    StartsWith,
    Strip,
    Switch,
    Time,
    TimeZone,
    TimeZoneInfo,
    Title,
    Union,
    Unique,
    Unordered,
    Upper,
    Url,
    Without,
    WriteOnce,
    message,
    raises,
    truth,
    validate,
)

if TYPE_CHECKING:
    # Eagerly visible to type-checkers so ``probatio.to_json_schema`` and friends
    # keep their real signatures, while at runtime they are re-exported lazily
    # (below) to keep a validate-only import cheap.
    from probatio.codecs import (
        UNSUPPORTED,
        from_json_schema,
        from_openapi,
        to_field_list,
        to_json_schema,
        to_openapi,
    )

# The codec layer costs more to import than the validation engine, and a plain
# ``import probatio`` for validation does not need it. Its public names are
# re-exported lazily (PEP 562): the submodule is imported on first access of one of
# its names, and the resolved attribute is cached as a real module global so later
# reads are free. Maps each re-exported name to the module it lives in.
_LAZY_NAMES = dict.fromkeys(
    (
        "UNSUPPORTED",
        "from_json_schema",
        "from_openapi",
        "to_field_list",
        "to_json_schema",
        "to_openapi",
    ),
    "probatio.codecs",
)


# ``__version__`` is resolved lazily from the installed package metadata on first
# access (PEP 562). A plain ``import probatio`` for validation never reads it, so
# it should not pay for the metadata lookup, which scans the installed dist-info
# (~20 ms). The resolved value is cached as a real module global afterwards. It
# falls back to "0.0.0" for a bare source-tree import (no install); the release
# workflow stamps the real version at publish time.
def __getattr__(name: str) -> object:
    """Resolve ``__version__`` and the lazy codec re-exports on first access."""
    if name == "__version__":
        from importlib import metadata  # noqa: PLC0415

        try:
            version = metadata.version("probatio")
        except metadata.PackageNotFoundError:  # pragma: no cover
            version = "0.0.0"
        globals()["__version__"] = version
        return version
    module_name = _LAZY_NAMES.get(name)
    if module_name is not None:
        from importlib import import_module  # noqa: PLC0415

        value = getattr(import_module(module_name), name)
        globals()[name] = value
        return value
    message = f"module {__name__!r} has no attribute {name!r}"
    raise AttributeError(message)


__all__ = [
    "ALLOW_EXTRA",
    "ASCII",
    "E164",
    "IBAN",
    "PREVENT_EXTRA",
    "REMOVE_EXTRA",
    "ULID",
    "UNDEFINED",
    "UNSUPPORTED",
    "UUID",
    "Abs",
    "Alias",
    "All",
    "AllInvalid",
    "AllOrNone",
    "Alpha",
    "Alphanumeric",
    "And",
    "Any",
    "AnyInvalid",
    "AsDate",
    "AsDatetime",
    "AsTime",
    "AsTimedelta",
    "AsTimezone",
    "AtLeastOne",
    "AtMostOne",
    "Base64",
    "BlockDeviceInvalid",
    "Boolean",
    "BooleanInvalid",
    "BuildPolicy",
    "Byte",
    "ByteLength",
    "Capitalize",
    "Check",
    "Clamp",
    "Coerce",
    "CoerceInvalid",
    "CompilePolicy",
    "Contains",
    "ContainsInvalid",
    "CreditCard",
    "DataURI",
    "DataclassSchema",
    "Date",
    "DateInvalid",
    "Datetime",
    "DatetimeInvalid",
    "Dedupe",
    "DefaultTo",
    "DictInvalid",
    "DirInvalid",
    "Divide",
    "Duration",
    "DurationInvalid",
    "Email",
    "EmailInvalid",
    "EndsWith",
    "EnsureList",
    "EnumInvalid",
    "EpochInvalid",
    "Equal",
    "Error",
    "ExactSequence",
    "ExactSequenceInvalid",
    "ExactlyOne",
    "Exclusive",
    "ExclusiveInvalid",
    "Extra",
    "ExtraKeysInvalid",
    "FalseInvalid",
    "FifoInvalid",
    "FileInvalid",
    "First",
    "Forbidden",
    "Fqdn",
    "FqdnUrl",
    "FromEpoch",
    "FromJSONString",
    "FromPercentage",
    "Hex",
    "HexColor",
    "HexInt",
    "Hostname",
    "HostnameInvalid",
    "IPAddress",
    "IPNetwork",
    "IPv4Address",
    "IPv6Address",
    "Immutable",
    "ImmutableInvalid",
    "In",
    "InInvalid",
    "Inclusive",
    "InclusiveInvalid",
    "Invalid",
    "IpInvalid",
    "IsBlockDevice",
    "IsDir",
    "IsFalse",
    "IsFifo",
    "IsFile",
    "IsRegex",
    "IsSocket",
    "IsSymlink",
    "IsTrue",
    "JSONString",
    "Join",
    "JsonInvalid",
    "Key",
    "Last",
    "Latitude",
    "Length",
    "LengthInvalid",
    "Literal",
    "LiteralInvalid",
    "Location",
    "Longitude",
    "Lower",
    "MacAddress",
    "MacAddressInvalid",
    "Marker",
    "Match",
    "MatchInvalid",
    "Maybe",
    "Modulo",
    "Msg",
    "MultipleInvalid",
    "MultipleOf",
    "MultipleOfInvalid",
    "Multiply",
    "Negative",
    "NoWhitespace",
    "NonEmpty",
    "NonNegative",
    "NormalizeMacAddress",
    "NotEnoughValid",
    "NotIn",
    "NotInInvalid",
    "Number",
    "Object",
    "ObjectInvalid",
    "Offset",
    "Optional",
    "Or",
    "PathExists",
    "PathInvalid",
    "Percentage",
    "Port",
    "Positive",
    "PrintableASCII",
    "Range",
    "RangeInvalid",
    "Remap",
    "Remove",
    "Replace",
    "Required",
    "RequiredFieldInvalid",
    "RequiredIf",
    "RequiredWith",
    "RequiredWithout",
    "Round",
    "RoundDown",
    "RoundUp",
    "ScalarInvalid",
    "Scale",
    "Schema",
    "SchemaError",
    "SchemaMixin",
    "Schemable",
    "Secret",
    "Self",
    "SequenceTypeInvalid",
    "Set",
    "SetTo",
    "Slug",
    "SlugInvalid",
    "SmallFloat",
    "Snap",
    "SocketInvalid",
    "SomeOf",
    "Sort",
    "Sorted",
    "Split",
    "StartsWith",
    "Strip",
    "Switch",
    "SymlinkInvalid",
    "Time",
    "TimeInvalid",
    "TimeZone",
    "TimeZoneInfo",
    "TimeZoneInvalid",
    "Title",
    "TooManyValid",
    "TrueInvalid",
    "TypeInvalid",
    "TypedDictSchema",
    "Undefined",
    "Union",
    "Unique",
    "Unordered",
    "Upper",
    "Url",
    "UrlInvalid",
    "UuidInvalid",
    "ValueInvalid",
    "VirtualPathComponent",
    "Without",
    "WriteOnce",
    "__version__",
    "create_dataclass_schema",
    "create_typeddict_schema",
    "current_context",
    "default_factory",
    "extra",
    "from_json_schema",
    "from_openapi",
    "get_build_policy",
    "get_compile_policy",
    "is_dataclass",
    "message",
    "probatio",
    "raises",
    "set_build_policy",
    "set_compile_policy",
    "to_field_list",
    "to_json_schema",
    "to_openapi",
    "truth",
    "validate",
]
