"""Built-in validators, grouped by kind.

Import them from ``probatio`` (or ``probatio.validators``); the submodules are an
internal organization detail.
"""

from __future__ import annotations

from probatio.validators.coerce import Boolean, Coerce, DefaultTo, Number, SetTo
from probatio.validators.combinators import (
    All,
    And,
    Any,
    Or,
    SomeOf,
    Switch,
    Union,
)
from probatio.validators.comparison import (
    Byte,
    Clamp,
    Contains,
    Equal,
    In,
    Latitude,
    Length,
    Literal,
    Longitude,
    MultipleOf,
    Negative,
    NonEmpty,
    NonNegative,
    NotIn,
    Percentage,
    Positive,
    Range,
    SmallFloat,
)
from probatio.validators.conditional import (
    Check,
    RequiredIf,
    RequiredWith,
    RequiredWithout,
)
from probatio.validators.decorators import message, raises, truth, validate
from probatio.validators.encoding import Base64, Hex, JSONString, YAMLString
from probatio.validators.formats import E164, IBAN, CreditCard, DataURI
from probatio.validators.identifiers import ULID, UUID, MacAddress
from probatio.validators.network import (
    Fqdn,
    Hostname,
    IPAddress,
    IPNetwork,
    IPv4Address,
    IPv6Address,
    Port,
)
from probatio.validators.predicates import (
    IsBlockDevice,
    IsDir,
    IsFalse,
    IsFifo,
    IsFile,
    IsSocket,
    IsSymlink,
    IsTrue,
    PathExists,
)
from probatio.validators.secret import Secret, SecretValue
from probatio.validators.strings import (
    ASCII,
    Alpha,
    Alphanumeric,
    ByteLength,
    Capitalize,
    Email,
    EndsWith,
    FqdnUrl,
    HexColor,
    IsRegex,
    Lower,
    Match,
    NoWhitespace,
    PrintableASCII,
    Replace,
    Slug,
    StartsWith,
    Strip,
    Title,
    Upper,
    Url,
)
from probatio.validators.structural import (
    EnsureList,
    ExactSequence,
    Maybe,
    Msg,
    Set,
    Sorted,
    Unique,
    Unordered,
)
from probatio.validators.temporal import (
    AsDate,
    AsDatetime,
    AsTime,
    Date,
    Datetime,
    Duration,
    Time,
    TimeZone,
)
from probatio.validators.transition import Immutable, WriteOnce

__all__ = [
    "ASCII",
    "E164",
    "IBAN",
    "ULID",
    "UUID",
    "All",
    "Alpha",
    "Alphanumeric",
    "And",
    "Any",
    "AsDate",
    "AsDatetime",
    "AsTime",
    "Base64",
    "Boolean",
    "Byte",
    "ByteLength",
    "Capitalize",
    "Check",
    "Clamp",
    "Coerce",
    "Contains",
    "CreditCard",
    "DataURI",
    "Date",
    "Datetime",
    "DefaultTo",
    "Duration",
    "Email",
    "EndsWith",
    "EnsureList",
    "Equal",
    "ExactSequence",
    "Fqdn",
    "FqdnUrl",
    "Hex",
    "HexColor",
    "Hostname",
    "IPAddress",
    "IPNetwork",
    "IPv4Address",
    "IPv6Address",
    "Immutable",
    "In",
    "IsBlockDevice",
    "IsDir",
    "IsFalse",
    "IsFifo",
    "IsFile",
    "IsRegex",
    "IsSocket",
    "IsSymlink",
    "IsTrue",
    "JSONString",
    "Latitude",
    "Length",
    "Literal",
    "Longitude",
    "Lower",
    "MacAddress",
    "Match",
    "Maybe",
    "Msg",
    "MultipleOf",
    "Negative",
    "NoWhitespace",
    "NonEmpty",
    "NonNegative",
    "NotIn",
    "Number",
    "Or",
    "PathExists",
    "Percentage",
    "Port",
    "Positive",
    "PrintableASCII",
    "Range",
    "Replace",
    "RequiredIf",
    "RequiredWith",
    "RequiredWithout",
    "Secret",
    "SecretValue",
    "Set",
    "SetTo",
    "Slug",
    "SmallFloat",
    "SomeOf",
    "Sorted",
    "StartsWith",
    "Strip",
    "Switch",
    "Time",
    "TimeZone",
    "Title",
    "Union",
    "Unique",
    "Unordered",
    "Upper",
    "Url",
    "WriteOnce",
    "YAMLString",
    "message",
    "raises",
    "truth",
    "validate",
]
